In [1]:
import pandas as pd 
import numpy as np

In [2]:
dataset=pd.read_csv("heart.csv")
dataset.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [3]:
dataset.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

In [5]:
dataset.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [6]:
dataset["ChestPainType"].unique()

array(['ATA', 'NAP', 'ASY', 'TA'], dtype=object)

In [7]:
dataset["ChestPainType"]=dataset["ChestPainType"].replace({
         'ATA':0,
         'NAP':1,
         'ASY':2,
         'TA':3
})

C:\Users\prash\AppData\Local\Temp\ipykernel_21528\2676116195.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dataset["ChestPainType"]=dataset["ChestPainType"].replace({

In [8]:
dataset["RestingECG"].unique()

array(['Normal', 'ST', 'LVH'], dtype=object)

In [9]:
dataset["RestingECG"]=dataset["RestingECG"].replace({
    'Normal':0,
    'ST':1,
    'LVH':2
})

C:\Users\prash\AppData\Local\Temp\ipykernel_21528\212885265.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dataset["RestingECG"]=dataset["RestingECG"].replace({

In [10]:
dataset["ExerciseAngina"].unique()

array(['N', 'Y'], dtype=object)

In [11]:
dataset["ExerciseAngina"]=dataset["ExerciseAngina"].replace({
    'N':0,
    'Y':1
})

C:\Users\prash\AppData\Local\Temp\ipykernel_21528\910037647.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dataset["ExerciseAngina"]=dataset["ExerciseAngina"].replace({

In [12]:
dataset["ST_Slope"].unique()

array(['Up', 'Flat', 'Down'], dtype=object)

In [13]:
dataset["ST_Slope"]=dataset["ST_Slope"].replace({
    'Up':0,
    'Flat':1,
    'Down':2
})

C:\Users\prash\AppData\Local\Temp\ipykernel_21528\2040439900.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dataset["ST_Slope"]=dataset["ST_Slope"].replace({

In [14]:
dataset.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,0,140,289,0,0,172,0,0.0,0,0
1,49,F,1,160,180,0,0,156,0,1.0,1,1
2,37,M,0,130,283,0,1,98,0,0.0,0,0
3,48,F,2,138,214,0,0,108,1,1.5,1,1
4,54,M,1,150,195,0,0,122,0,0.0,0,0

In [15]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    int64
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    int64
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    int64
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    int64
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(10), object(1)
memory usage: 86.2+ KB

In [16]:
x=dataset.iloc[:,[2,3,4,5,6,7,8,9,10]]
y=dataset.iloc[:,11]

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [18]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [19]:
from sklearn.svm import SVC
svc=SVC()
svc.fit(x_train,y_train)
y_pred=svc.predict(x_test)
y_pred

array([1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 1])

In [20]:
dataset.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,0,140,289,0,0,172,0,0.0,0,0
1,49,F,1,160,180,0,0,156,0,1.0,1,1
2,37,M,0,130,283,0,1,98,0,0.0,0,0
3,48,F,2,138,214,0,0,108,1,1.5,1,1
4,54,M,1,150,195,0,0,122,0,0.0,0,0

In [21]:
chestpaintype=int(input("Enter your chestpain type('ATA':0,'NAP':1,'ASY':2,'TA':3): "))
restingbp=int(input("Enter your resting BP: "))
cholesterol=int(input('Enter your cholesterol level: '))
fastingbs=int(input("Enter your fasting BS(0-1): "))
restingecg=int(input("Enter you resting ECG('Normal':0,'ST':1,'LVH':2): "))
maxhr=int(input("Enter your max HR: "))
exerciseangina=int(input("Enter your exercise angina( 'N':0,'Y':1): "))
oldpeak=int(input("Enter your old peak: "))
stslope=int(input("Enter your st slope('Up':0,'Flat':1,'Down':2): "))
new_patient=[[chestpaintype,restingbp,cholesterol,fastingbs,restingecg,maxhr,exerciseangina,oldpeak,stslope]]
new_patient_scaled=sc.transform(new_patient)
prediction=svc.predict(new_patient_scaled)
print("Here the output 0 means not heart disease but 1 means heart disease: ",prediction)
if(prediction==0):
    print("No heart disease and you are already fine!")
else:
    print("Heart issue!")

Enter your chestpain type('ATA':0,'NAP':1,'ASY':2,'TA':3):  0
Enter your resting BP:  120
Enter your cholesterol level:  145
Enter your fasting BS(0-1):  0
Enter you resting ECG('Normal':0,'ST':1,'LVH':2):  1
Enter your max HR:  145
Enter your exercise angina( 'N':0,'Y':1):  0
Enter your old peak:  12
Enter your st slope('Up':0,'Flat':1,'Down':2):  0

Here the output 0 means not heart disease but 1 means heart disease:  [1]
Heart issue!

C:\Users\prash\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [22]:
from sklearn.metrics import (accuracy_score,precision_score,recall_score,f1_score,roc_auc_score,confusion_matrix)
acc=accuracy_score(y_test,y_pred)
print("accuracy score= ",acc)
prec=precision_score(y_test,y_pred)
print("precision score= ",prec)
rec=recall_score(y_test,y_pred)
print("recall score= ",rec)
f1=f1_score(y_test,y_pred)
print("f1 score= ",f1)
auc=roc_auc_score(y_test,y_pred)
print("roc auc score= ",auc)
confuse=confusion_matrix(y_test,y_pred)
print("confusion matrix: \n",confuse)

accuracy score=  0.8315217391304348
precision score=  0.8333333333333334
recall score=  0.8878504672897196
f1 score=  0.8597285067873304
roc auc score=  0.8205486102682364
confusion matrix:
 [[58 19]
 [12 95]]